version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: test
          command: yarn ng test --sr --no-progress

