version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore-cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: test
          command: yarn ng test --sr --no-progress
      - run:
          name: lint
          command: yarn ng lint
      - save-cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      # Deploy production
      - deploy:
          command: |
            sh scripts/publish.sh;

